### ISSUE TITLE
Missing modules when running as root

### ISSUE THREAD

**Issue by chambln** [qwerty-fr/kalamine#5]
I can install and run xkalamine just fine as my regular user.

    $ git clone https://github.com/qwerty-fr/kalamine
    $ cd kalamine
    $ poetry install
    $ poetry run xkalamine
    Usage: xkalamine [OPTIONS] COMMAND [ARGS]...
    ...

But then as root, the installed modules are not available.

    # poetry run xkalamine
    Traceback (most recent call last):                                                   
      File "<string>", line 1, in <module>                                               
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module       
        return _bootstrap._gcd_import(name[level:], package, level)                      
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import                    
      ...
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed       
      File "/home/greg/src/kalamine/kalamine/__init__.py", line 2, in <module>                 
        from .layout import KeyboardLayout                                               
      File "/home/greg/src/kalamine/kalamine/layout.py", line 10, in <module>                  
        import yaml                                                                      
    ModuleNotFoundError: No module named 'yaml'

The only way I can get layouts installed properly is by installing the dependencies *as root* using poetry

    # poetry install
    # poetry run xkalamine
    Usage: xkalamine [OPTIONS] COMMAND [ARGS]...
    ...

which is not ideal. Root permissions are only really needed in order to modify the system's keyboard layout files, right? Maybe it's better to produce a diff which the user can then apply by running `patch`(1) as root, or produce a complete symbols file which can be installed using `cp`(1) or whatever as root.

**Comment by chambln** [comment]
Related: fabi1cazenave/kalamine#22 (draft PR: Install system-wide without running xkalamine as root)

**Comment by devnoname120** [comment]
Can you try the recommendation of ChatGPT?

<img width="728" alt="image" src="https://user-images.githubusercontent.com/2824100/206592077-556f3102-c0c3-42ba-a6c8-dff9e66cdcae.png">

**Comment by devnoname120** [comment]
@chambln Interestingly, it works just fine here:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/2824100/206593254-f45a845c-1fce-42f4-9c05-04b06ae5c3ff.png">

Anyway, I don't think that this issue is related to https://github.com/qwerty-fr/kalamine, but it's more a question about how to use Poetry. I'll keep it open so that we can update the `README.md` file once we have a solution.
